sudo: false
language: python
services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

before_install:
  - sudo service postgresql stop
  - sed -e 's/^port.*/port = 5432/' /etc/postgresql/10/main/postgresql.conf > postgresql.conf
  - sudo chown postgres postgresql.conf
  - sudo mv postgresql.conf /etc/postgresql/10/main
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql start 10
  # wait for the postgres docker to be running
  - while ! pg_isready -h localhost -p 5432 -q -U postgres; do "Postgres is unavailable - sleeping"; sleep 1; done;
  - psql -c "CREATE USER simpleml with password 'simpleml' SUPERUSER;" -U postgres

install:
 - pip install psycopg2
 - pip install coveralls
 - pip install tox-travis

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

script:
  - coverage run setup.py test

matrix:
  include:
    # - python: 2.7
    #   env: TOXENV=py27
    # - python: 3.4
    #   env: TOXENV=py34
    # - python: 3.5
    #   env: TOXENV=py35
    # - python: 3.6
    #   env: TOXENV=py36
    # - env: TOXENV=flake8
    - install: pip install flake8
      script: flake8 .

  allow_failures:
    - python: 3.7
      # env: TOXENV=py37
      dist: xenial
      sudo: true
      script: python setup.py test
    - python: pypy
      script: python setup.py test
      # env: TOXENV=pypy
    - python: pypy3
      script: python setup.py test
      # env: TOXENV=pypy3

# script: tox
after_success:
  - coverage combine
  - coveralls
