services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

before_script:
  # wait for the postgres docker to be running
  - while ! pg_isready -h localhost -p 5432 -q -U postgres; do "Postgres is unavailable - sleeping"; sleep 1; done;

sudo: false
language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: pypy
      env: TOXENV=pypy
    - python: pypy3
      env: TOXENV=pypy3
    - env: TOXENV=flake8

install:
 - pip install coveralls
 - pip install tox-travis
script: tox
after_success: coveralls
